config:
    paths:
        'json': 'bundles/ekynarequirejs/plugin/json'
        'text': 'bundles/ekynarequirejs/plugin/text'
        'domReady': 'bundles/ekynarequirejs/plugin/domReady'
build:
    include: ['json', 'text', 'domReady']
